-- MySQL Script generated by MySQL Workbench
-- Sun Oct  9 00:25:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Clinics` ;

-- ---------------------------------EventCategory--------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Clinics` DEFAULT CHARACTER SET utf8 ;
USE `Clinics` ;

-- -----------------------------------------------------
-- Table `Clinics`.`EventCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinics`.`EventCategory` (
  `eventCategoryId` INT NOT NULL,
  `eventCategoryName` VARCHAR(100) NOT NULL,
  `eventCategoryDescription` VARCHAR(500) NULL,
  `eventDuration` INT NOT NULL,
  PRIMARY KEY (`eventCategoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinics`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinics`.`Event` (
  `bookingId` INT NOT NULL auto_increment,
  `bookingName` VARCHAR(100) NOT NULL,
  `bookingEmail` VARCHAR(50) NULL,
  `eventStartTime` DATETIME NOT NULL,
  `eventNote` VARCHAR(500) NULL,
  `eventDuration` INT NOT NULL,
  `eventCategoryId` INT NOT NULL,
  `fileName` VARCHAR(500) NULL,
  PRIMARY KEY (`bookingId`),
  INDEX `fk_Event_EventCategory_idx` (`eventCategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_Event_EventCategory`
    FOREIGN KEY (`eventCategoryId`)
    REFERENCES `Clinics`.`EventCategory` (`eventCategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Clinics`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinics`.`user` (
  `userID` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
	`createdOn` datetime not null default current_timestamp ,
	`updatedOn` datetime not null default current_timestamp on update current_timestamp ,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinics`.`EventCategoryOwner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinics`.`EventCategoryOwner` (
  `eventCategoryId` INT NOT NULL,
  `userID` INT NOT NULL,
  `id` INT NOT NULL auto_increment,
  PRIMARY KEY (`id`),
  INDEX `fk_EventCategory_has_user_user1_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_EventCategory_has_user_EventCategory1_idx` (`eventCategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_EventCategory_has_user_EventCategory1`
    FOREIGN KEY (`eventCategoryId`)
    REFERENCES `Clinics`.`EventCategory` (`eventCategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventCategory_has_user_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `Clinics`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
